### ISSUE TITLE
Days without Watch logic

### ISSUE THREAD

**Issue by tcconnally** [ASK-ME-ABOUT-LOOM/purgeomatic#22]
Sorry if this is the wrong avenue. I have a question about the "Days without Watch" logic.

It looks like it takes the date from Tautulli for when the media was "added" to use for the DAYS_WITHOUT_WATCH.

I started using Tautulli after my library was already pretty large, I think a feature to parse "Added via Overseerr request and not watched within X days" would also be useful.

If that is already part of the logic, please disregard.

Excellent script, BTW!!! So useful!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
I'm actually dealing with a similar issue, where I partially rebuilt my metadata in Taurulli (due to a mistake when upgrading from an old server to a new one 😅) and have a large swath of media that is keeping me from using the `DAYS_WITHOUT_WATCH` functionality. 

I don't _think_ Overseerr provides that kind of metadata. Put another way, what do you do about a request that someone puts in for a show that has yet to release, then takes longer than 60 days to download? I'm not sure that Overseerr keeps both 'date requested' and 'date available' metadata.

I'm currently out of town, but I'll check on this next week.

**Comment by tcconnally** [comment]
That makes sense. I have Overseerr set to tag anything it adds to Radarr along with the username of the Requestor. Maybe a flag to exclude Oeverseerr adds or adds from a specific User? Basically separate "Old media that I've had forever" and "Stuff people requested but didn't watch" or "Don't delete requests/don't delete requests by X User"?

**Comment by ASK-ME-ABOUT-LOOM** [comment]
After reviewing the Overseerr API, I'm not sure that what you want is possible. It has `created_at` and `updated_at` metadata, but I'm not 100% clear on when `updated_at` is actually touched. Honestly, adding support for tags from one of the arrs is not something I'm interested in pursuing as it will likely involve quite a lot of edge-case management and I'm lazy. 

If you're looking to keep media from being deleted, I have a number of suggestions:

1) If you have a small quantity, use the protected file as defined in the README.md. 

2) If you have a large quantity, consider migrating it to another library that isn't scanned by this tool.

3) Try a more complicated tool like [Maintainerr](https://github.com/jorenn92/Maintainerr) for more precise management.

**Comment by tcconnally** [comment]
I completely understand. You tool has helped me immensely in cleaning up my library (like 16TB of media out of ~90) and I made prodigious use of the protected file as I was parsing through the items it flagged. I have it set now to Dry Run on my NAS every month to see what is aging out.

I'm no familiar with Maintainerr, but I'll definitely give it a look! Always looking to tweak and fiddle with my Plex setup.

Thanks again for the awesome script, and the prompt response!
