### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by sameep22** [ASK-ME-ABOUT-LOOM/purgeomatic#6]
Hi,

First I'd like to thank you for this project. I have been looking for something like this for a long time to keep my library well maintained. This is exactly what I needed.

I am sorry if I did not put this in the right place. I think this is a feature request, but I dunno where to make that.

I can see that docker is supported, however, I was unable to see any instructions for docker-compose. Is it possible to pass these variables using a docker-compose file? 

Thanks,

**Comment by ASK-ME-ABOUT-LOOM** [comment]
You're certainly welcome to use docker-compose, which [supports environment variables](https://docs.docker.com/compose/environment-variables/set-environment-variables/) in the docker-compose.yml.

The software was designed to be called directly like a script, not to be kept running as part of a larger infrastructure/container deployment, which is why instructions for docker-compose were not included.
