### ISSUE TITLE
delete.tv.unwatched.py deleting same series with longer name

### ISSUE THREAD

**Issue by segunchand** [ASK-ME-ABOUT-LOOM/purgeomatic#9]
First of all, great tool, thank you very much for creating it.

One small bug report that I discovered while using it:
When I was trying to delete a series (in this case "The office"), the script automatically deleted the series with the same name, but longer (in this case "The Office (US)"), the one that should have been deleted stayed at the location.
I assume there might be an issue with the name recognition.

The exact steps I took to arrive at this conclusion:
- ran the delete.tv.unwatched.py with dry-run (here "The Office" was included)
- ran the script and it confirmed "DELETED: The Office"
- after I ran it again to confirm everything was deleted, "The Office" was still included in the dry-run
- I checked my sonarr, plex and tautulli pages and can confirm, "The Office (US)" was deleted and "The Office" was still there.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
In an effort to explain why I have to do title-based searches in order to pull content to delete, I just now discovered how to pull TMDB IDs from Tautulli that will allow me to get rid of the janky title-based search I'm currently using. I'll probably be able to get this coded during the next week and I'll reply here when the updated code is available.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
This turned out to be easier to fix than I thought. In the code before, I was doing partial matching of media item titles under the assumption that using the full title in a query would still result in the best match. Obviously that's causing problems, so I've switched to an exact match. 

I briefly looked at pulling the TMDB ID from Tautulli's metadata, but it turns out that not every media item has TMDB/IMDB/TVDB items associated with it - many items are just blank! Ultimately, exact matching on media title seems like the best approach. 

Please have a look and confirm it's working for you.

**Comment by J0E6469** [comment]
@ASK-ME-ABOUT-LOOM  I'm not well-versed in GitHub and couldn't find a way to message you directly, so I'm reaching out here. Was this issue ever fixed?

Yesterday, I noticed that when I ran the script to delete TV shows, some were marked as DELETED, but when I checked my media folder, they were still there. Out of 147 series scheduled for deletion, about 10 remained, and I had to manually delete their folders.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
It's been a while, but if memory serves, ultimately there is a measure of inexactitude with matching records when the metadata is not in place. The best solution is refreshing the metadata in your library. I've settled on weekly forced metadata refreshes for my library via cronjob and that mostly helps, but ultimately, if the tvdbid/moviedbid doesn't exist, this script is doing a best effort match and sometimes it's not going to work. 

The way a delete is achieved is via API calls to radarr/sonarr, and (again, if memory serves) they don't provide tons of feedback about whether or not media exists when you make a call to delete. Sometimes this script just straight-up gets it wrong and there's really no way to be 100% certain that I can think up.
